'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../engine/trend');
const T=require('../app/tracker');
const D=require('../app/marketdata');
let count=0;const failures=[];
function test(name,fn){try{fn();count++;console.log('PASS '+name);}catch(e){failures.push(name);console.log('FAIL '+name+' — '+String(e.message).split('\n')[0]);}}
const DAY=86400000;
// Candle 1D sintetis: drift per hari + gelombang, deterministik.
const series=(n,drift,amp=0.02,start=100)=>{let p=start;return Array.from({length:n},(_,i)=>{const o=p;p=p*(1+drift+amp*Math.sin(i/5));const c=p;return {t:i*DAY,ct:(i+1)*DAY-1,open:o,close:c,high:Math.max(o,c)*1.01,low:Math.min(o,c)*0.99,volume:1000,quoteVolume:1000*c,takerBuyQuote:600*c};});};
const up=series(400,0.004),down=series(400,-0.004),flat=series(400,0,0.03);
// Implementasi referensi diambil langsung dari skrip riset yang diuji (research/trend-score-2026-10-07/tf.js).
const src=fs.readFileSync(__dirname+'/../research/trend-score-2026-10-07/tf.js','utf8');
const pick=name=>{const m=src.match(new RegExp('^(?:const '+name+'=.*|function '+name+'\\(c\\)\\{[\\s\\S]*?\\n\\})$','m'));if(!m)throw new Error('referensi '+name+' tidak ditemukan');return m[0];};
const ref=vm.runInNewContext([pick('ewma'),pick('ewstd'),pick('cap'),pick('forecasts')].join('\n')+';forecasts');
test('skor aplikasi identik dengan implementasi riset yang diuji (tren naik, turun, datar)',()=>{for(const c of [up,down,flat]){const a=E.series(c).combined,b=ref(c);assert.equal(a.length,b.length);for(let i=0;i<a.length;i++){if(a[i]==null||b[i]==null){assert.equal(a[i],b[i]);continue;}assert(Math.abs(a[i]-b[i])<1e-9,'beda di indeks '+i);}}});
test('tren naik memberi sinyal LONG, tren turun SHORT, pasar datar tanpa sinyal',()=>{const now=400*DAY;const u=E.evaluate(up,{now}),d=E.evaluate(down,{now}),f=E.evaluate(flat,{now});assert.equal(u.side,'long');assert(u.forecast>=10);assert.equal(d.side,'short');assert(d.forecast<=-10);assert.equal(f.plan,null);assert.equal(f.decision,'SKIP');});
test('skor dan setiap aturan dibatasi ±20',()=>{const s=E.series(series(400,0.03,0));for(const r of s.rules)for(const v of r.v)if(v!=null)assert(Math.abs(v)<=20);for(const v of s.combined)if(v!=null)assert(Math.abs(v)<=20);});
test('rencana: entry = harga saat sinyal, stop awal = entry ∓ 0,5 × volatilitas harga tahunan, tanpa TP',()=>{const now=400*DAY,e=E.evaluate(up,{now,lastPrice:500});assert.equal(e.plan.entry,500);assert(Math.abs(e.gap-0.5*e.pvolDaily*Math.sqrt(365))<1e-9);assert(Math.abs(e.plan.sl-(500-e.gap))<1e-9);assert.equal(e.plan.tp,null);assert.equal(e.plan.trailing,true);const s=E.evaluate(down,{now,lastPrice:50});assert(Math.abs(s.plan.sl-(50+s.gap))<1e-9);});
test('candle yang belum close diabaikan; data < 300 hari tidak memberi skor',()=>{const c=up.slice(0,350);const open=Object.assign({},c[c.length-1],{ct:999*DAY});const e=E.evaluate(c.slice(0,-1).concat(open),{now:349*DAY+1});assert.equal(e.candles.length,349);assert.equal(E.evaluate(up.slice(0,250),{now:400*DAY}).forecast,null);});
test('kausal: skor hari lalu tidak berubah saat candle baru ditambahkan',()=>{const a=E.series(up.slice(0,330)).combined,b=E.series(up).combined;for(let i=0;i<330;i++)assert.equal(a[i],b[i]);});
test('hasil hitung skor dipakai ulang untuk array candle yang sama, dihitung ulang saat ada candle baru',()=>{const c=up.slice();const a=E.evaluate(c,{now:400*DAY});const t0=process.hrtime.bigint();for(let k=0;k<50;k++)E.evaluate(c,{now:400*DAY});const ms=Number(process.hrtime.bigint()-t0)/1e6;assert(ms<200,'evaluasi ulang terlalu lambat: '+ms.toFixed(0)+' ms');const longer=c.concat(series(401,0.004).slice(400).map(x=>Object.assign({},x,{t:400*DAY,ct:401*DAY-1})));const b=E.evaluate(longer,{now:401*DAY});assert.equal(b.candles.length,401);assert.equal(a.forecast,E.evaluate(c,{now:400*DAY}).forecast);});
// ---------- Tracker untuk rencana tren ----------
const plan=(side,entry,gap,at)=>({side,plan:{entry,sl:side==='long'?entry-gap:entry+gap,initialSl:side==='long'?entry-gap:entry+gap,gap,risk:gap,tp:null,rr:null,trailing:true,forecastAtSignal:side==='long'?12:-12,signalAt:at}});
test('tracker: ARMED → RUNNING saat entry tersentuh; tanpa TP posisi hanya keluar di stop',()=>{const r=T.create('X',plan('long',100,10,5),0);assert.equal(r.id,'X|long|5');assert.equal(r.engine,'trend-v1');T.advance(r,{low:99,high:101},1);assert.equal(r.status,'running');assert.equal(r.filledAt,1);assert.equal(r.peak,100);T.advance(r,{low:100,high:500},2);assert.equal(r.status,'running');T.advance(r,{low:89,high:95},3);assert.equal(r.outcome,'sl');assert.equal(r.r,-1);assert.equal(T.journalStatus(r),'loss');});
test('trailing stop naik mengikuti close 1D tertinggi, tidak pernah turun; keluar dalam untung = win',()=>{const r=T.create('X',plan('long',100,10,5),0);T.advance(r,{low:100,high:100},1);const day=(ct,close)=>({ct,close});E.trail(r,[day(0,90),day(2,120),day(3,115)]);assert.equal(r.peak,120);assert.equal(r.sl,110);E.trail(r,[day(2,120),day(3,105)]);assert.equal(r.sl,110);T.advance(r,{low:109,high:116},4);assert.equal(r.outcome,'sl');assert.equal(r.exit,110);assert(Math.abs(r.r-1)<1e-9);assert.equal(T.journalStatus(r),'win');});
test('trailing stop SHORT (cermin): turun mengikuti close terendah',()=>{const r=T.create('X',plan('short',100,10,5),0);T.advance(r,{low:100,high:100},1);E.trail(r,[{ct:2,close:80},{ct:3,close:85}]);assert.equal(r.peak,80);assert.equal(r.sl,90);T.advance(r,{low:85,high:91},4);assert.equal(r.outcome,'sl');assert(r.r>0);});
test('trailing hanya untuk posisi RUNNING; candle sebelum fill diabaikan',()=>{const a=T.create('X',plan('long',100,10,5),0);E.trail(a,[{ct:2,close:200}]);assert.equal(a.sl,90);const r=T.create('X',plan('long',100,10,5),0);T.advance(r,{low:100,high:100},10);E.trail(r,[{ct:5,close:300},{ct:11,close:104}]);assert.equal(r.peak,104);assert.equal(r.sl,94);});
test('satu pair satu rencana aktif; ARMED gugur bila engine tidak lagi menghasilkannya',()=>{const run=T.create('X',plan('long',100,10,5),0);T.advance(run,{low:100,high:100},1);assert.equal(T.admit([run],T.create('X',plan('short',100,10,6),2)),false);assert.equal(T.admit([run],T.create('Y',plan('long',100,10,6),2)),true);const a=T.create('X',plan('long',100,10,5),0);assert.equal(T.expire(a,T.create('X',plan('long',100,10,6),1),2),true);assert.equal(a.outcome,'void');assert.equal(T.expire(run,null,3),false);});
test('rencana engine lama (dengan TP) tetap ditangani tracker',()=>{const r=Object.assign(T.create('X',plan('long',100,10,5),0),{tp:130});T.advance(r,{low:100,high:100},1);T.advance(r,{low:101,high:131},2);assert.equal(r.outcome,'tp');assert.equal(T.journalStatus(r),'win');});
// ---------- Data pasar pelengkap ----------
const trendBars=(n,step)=>Array.from({length:n},(_,i)=>{const p=100+i*step;return {open:p,close:p+step*0.8,high:p+Math.abs(step),low:p-Math.abs(step)*0.2,volume:1};});
test('data pasar: ADX tinggi dengan +DI dominan saat naik, cermin saat turun',()=>{const u=D.adx(trendBars(60,1));assert(u.adx>40);assert(u.plusDI>u.minusDI);const d=D.adx(trendBars(60,-1));assert(d.minusDI>d.plusDI);assert.equal(D.adx(trendBars(20,1)),null);});
test('data pasar: CVD = jumlah (2 × taker buy quote − quote volume); metrik dari candle 1D',()=>{const c=[{takerBuyQuote:60,quoteVolume:100},{takerBuyQuote:30,quoteVolume:100},{takerBuyQuote:80,quoteVolume:100}];assert.equal(D.cvd(c,3),40);assert.equal(D.cvd(c,4),null);const m=D.metrics({candles:up});assert(m.adx1d&&m.adx1d.adx>0);assert(Math.abs(m.cvd1d-0.2*up.at(-1).quoteVolume)<1e-6);assert(Number.isFinite(m.cvd7d));});
test('data pasar: orderbook dan parsing respons Binance defensif',()=>{const b=D.depth({bids:[['100','3']],asks:[['100.1','1']]});assert.equal(Math.round(b.bidPct),75);const p=D.parse([[{sumOpenInterestValue:'100'},{sumOpenInterestValue:'110'}],[{longShortRatio:'1.5',longAccount:'0.6'}],null,[{buySellRatio:'1.2'}],null]);assert.equal(p.oiUsd,110);assert.equal(p.accounts.longPct,60);assert.equal(p.topPositions,null);assert.equal(p.book,null);});
test('universe: Top 250 menurut volume 24 jam, urutan deterministik',()=>{const rows=Array.from({length:280},(_,i)=>({symbol:'P'+String(i).padStart(3,'0'),quoteVolume:i}));const r=E.rankUniverse(rows);assert.equal(r.length,250);assert.equal(r[0].quoteVolume,279);assert.equal(E.rankUniverse([{symbol:'B',quoteVolume:1},{symbol:'A',quoteVolume:1}])[0].symbol,'A');});
if(failures.length){console.log('\n'+failures.length+' pemeriksaan GAGAL.');process.exit(1);}
console.log('\n'+count+' pemeriksaan engine tren / tracker / data pasar lulus.');
