'use strict';
const assert=require('node:assert/strict');
const M=require('../engine/malomo');
const T=require('../app/tracker');
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const prices=[8,9,10,12,10,9,8,9,10,11,10,9,9.5,10,11,12,13,15,13,12,11,12,13];
const candles=a=>a.map((p,i)=>({open:p,close:p,high:p+.2,low:p-.2,volume:10,t:i*1000,ct:i*1000+999}));
const base=candles(prices);
const append=(c,a)=>c.concat(a.map((p,i)=>({open:p,close:p,high:p+.4,low:p-.4,volume:1,t:(c.length+i)*1000,ct:(c.length+i)*1000+999})));
const mirror=c=>c.map(x=>({...x,open:40-x.open,close:40-x.close,high:40-x.low,low:40-x.high}));
test('fractal cannot confirm before two right closes',()=>{assert.equal(M.pivots(base.slice(0,5)).length,0);assert.equal(M.pivots(base.slice(0,6))[0].confirmedAt,5);});
test('structure seeds bullish and mirror bearish',()=>{assert.equal(M.structure(base).bias,'bullish');assert.equal(M.structure(mirror(base)).bias,'bearish');});
test('internal swings do not move protected swing',()=>{const s=M.structure(base);assert.equal(s.protectedSwing.index,11);assert.equal(s.swings.find(x=>x.index===20).role,'internal');});
test('protected origin is already confirmed at break',()=>{const s=M.structure(append(base,[14,16]));const b=s.events.filter(x=>x.type==='BREAKOUT').at(-1);assert(s.protectedSwing.confirmedAt<=b.index);assert.equal(s.protectedSwing.index,20);});
test('new structural extreme waits for fractal confirmation',()=>{assert.equal(M.structure(append(base,[14,16])).high.index,17);assert.equal(M.structure(append(base,[14,16,15,14])).high.index,24);});
test('internal continuation preserves structural high and protected low',()=>{const st=M.structure(append(base,[12,13.5,12,11.5,12,14]));assert.equal(st.phase,'kelanjutan lokal');assert.equal(st.high.index,17);assert.equal(st.protectedSwing.index,11);});
test('reversal requires confirmed break then fresh opposite structure',()=>{const st=M.structure(append(base,[8,8.5,7,6,7,9,8,7,6.5,5,6,8,7,6,4,5,6]));assert.equal(st.bias,'bearish');assert(st.events.some(x=>x.type==='REVERSAL_CONFIRMED'));const rev=st.events.find(x=>x.type==='REVERSAL_CONFIRMED');assert(st.events.some(x=>x.type==='STRUCTURE_BROKEN'&&x.index<rev.index));});
test('wick sweep does not break structure',()=>{const c=append(base,[9]);c.at(-1).low=7;const s=M.structure(c);assert.equal(s.bias,'bullish');assert.equal(s.pending,null);assert(s.sweeps.some(x=>x.side==='low'));});
test('close alone leaves direction pending; weak volume is not a gate',()=>{const s=M.structure(append(base,[8]));assert.equal(s.status,'menunggu konfirmasi');assert.equal(s.bias,'bullish');});
test('outside retest close confirms break without auto reversal',()=>{const s=M.structure(append(base,[8,8.5]));assert.equal(s.status,'patah terkonfirmasi');assert.equal(s.bias,'neutral');});
test('break retest mirror',()=>{const s=M.structure(mirror(append(base,[8,8.5])));assert.equal(s.status,'patah terkonfirmasi');assert.equal(s.bias,'neutral');});
test('reclaim cancels pending',()=>{assert.equal(M.structure(append(base,[8,9])).pending,null);});
test('outside close without retest remains pending',()=>{assert(M.structure(append(base,[8,7])).pending);});
test('EMA positions cannot change structural direction',()=>{const d=M.frame(base),h=M.frame(base);d.ema={21:100,30:100,50:100};assert.equal(M.direction(d,h),'bullish');h.structure.bias='bearish';assert.equal(M.direction(d,h),null);});
test('open candles excluded',()=>{assert.equal(M.closed(base,base.at(-2).ct).length,base.length-1);});
test('RVOL excludes evaluated candle',()=>{const c=candles(Array.from({length:21},(_,i)=>10+i));c.at(-1).volume=100;assert.equal(M.evidence(c).rvol20,10);});
test('event evidence evaluates event candle not latest candle',()=>{const c=append(base,[8,7]);c.at(-1).volume=1000;const f=M.frame(c);assert.notEqual(f.eventEvidence.rvol20,f.evidence.rvol20);});
test('ATR is independent measurement',()=>{assert(M.atr(base)>0);assert.equal(M.evidence(base).candleMagnitude,null);});
test('universe takes top 250 with deterministic ties and no minimum volume',()=>{const rows=Array.from({length:280},(_,i)=>({symbol:'P'+String(i).padStart(3,'0'),quoteVolume:i}));const r=M.rankUniverse(rows);assert.equal(r.length,250);assert.equal(r[0].quoteVolume,279);assert.equal(M.rankUniverse([{symbol:'X',quoteVolume:0}]).length,1);assert.equal(M.rankUniverse([{symbol:'B',quoteVolume:1},{symbol:'A',quoteVolume:1}])[0].symbol,'A');});
test('top150 total ranks pending candidates by quote volume only',()=>{const rows=Array.from({length:170},(_,i)=>({symbol:'P'+i,quoteVolume60m:i,evaluation:{bias:i%2?'bullish':'bearish',status:'menunggu konfirmasi',rvol:0}}));const r=M.rankCandidates(rows);assert.equal(r.length,150);assert.equal(r[0].quoteVolume60m,169);assert(r.some(x=>x.evaluation.bias==='bearish'));});
test('touch alone does not validate entry',()=>{assert.equal(M.trigger(candles([10,10.5,11,10.5]),{low:9,high:10.3,createdAt:0},'long').ready,false);});
test('entry needs swing formed during zone test and confirmed before close break',()=>{const c=candles([10,11,12,11,10.5,13]);const tr=M.trigger(c,{low:9.5,high:10.3,createdAt:0},'long');assert.equal(tr.ready,true);assert.equal(tr.index,5);assert.equal(M.trigger(c.slice(0,5),{low:9.5,high:10.3,createdAt:0},'long').ready,false);});
test('entry mirror',()=>{assert(M.trigger(mirror(candles([10,11,12,11,10.5,13])),{low:29.7,high:30.5,createdAt:0},'short').ready);});
test('zone cannot validate retroactive entry',()=>{assert.equal(M.trigger(candles([10,11,12,11,10.5,13]),{low:9.5,high:10.3,createdAt:5000},'long').ready,false);});
test('nearest structural target cannot be skipped to improve RR',()=>{assert.equal(M.plan('long',10,9,[11,20],.01),null);});
test('minimum RR boundary and structural SL',()=>{const p=M.plan('long',10,9.1,[12.2],.1);assert(p);assert.equal(p.sl,9);assert.equal(p.rr,2.2);assert.equal(M.plan('long',10,9.1,[12.19],.1),null);const q=M.plan('short',30,30.9,[27.8],.1);assert(q);assert.equal(q.sl,31);});
const evaluation={side:'long',trigger:{ready:true,ct:10},plan:M.plan('long',10,9,[14],.01)};
test('tracker refuses unconfirmed plan',()=>{assert.equal(T.create('X',{plan:null,trigger:{ready:false}},0),null);});
test('tracker starts armed and SL exits independently of structural retest',()=>{const r=T.create('X',evaluation,0);T.advance(r,{low:10,high:10},1);assert.equal(r.status,'running');T.advance(r,{low:8,high:9},2);assert.equal(r.outcome,'sl');assert.equal(r.r,-1);});
test('ambiguous OHLC gives SL priority',()=>{const r=T.create('X',evaluation,0);T.advance(r,{low:10,high:10},1);T.advance(r,{low:8,high:15},2);assert.equal(r.outcome,'sl');});
test('fill bar cannot claim TP before fill',()=>{const r=T.create('X',evaluation,0);T.advance(r,{low:10,high:15},1);assert.equal(r.status,'running');T.advance(r,{low:10,high:15},2);assert.equal(r.outcome,'tp');});
test('bypassed entry becomes void',()=>{const r=T.create('X',evaluation,0);T.advance(r,{low:14,high:15},1);assert.equal(r.outcome,'void');});
test('causal prefix decisions remain independent of future candles',()=>{for(let n=8;n<base.length;n++){const prefix=base.slice(0,n),a=M.structure(prefix);const live=M.closed(base,prefix.at(-1).ct);assert.deepEqual(M.structure(live),a);assert(a.swings.every(s=>s.confirmedAt<n));}});
console.log('\n'+count+' engine/tracker checks passed.');
